### ISSUE TITLE
Delete Repository

### ISSUE THREAD

**Issue by LaylaMeower** [Pridecraft-Studios/PridecraftStudios-site#1]
the repository [pridecraft-studios.github.io](https://github.com/Pridecraft-Studios/pridecraft-studios.github.io) is the official repository for the website. Pages are created _inside_ of the other repositories - unless you want the site to transfer here - will be possible, but we'll be unable to create pages from other repositories - in that case, transfer the repository to the @Pridecraft-Studios/web-development team.

**Comment by Nu-Git** [comment]
Being Deleted
